os: windows
language: cpp
env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
install:
  - choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional"
  - choco install visualstudio2019-workload-vctools
script:
  - export PATH=$MSBUILD_PATH:$PATH
  - MSBuild.exe -p:Configuration=Release -p:Platform=x64 LR4.sln
  - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\vstest.console.exe" LR4/Release/LR4.exe /Platform:x64
