version: 0.1.{build}
image: Visual Studio 2019
build_script:
- ps: >-
    .\build.ps1
test:
  # only assemblies to test
  assemblies:
    only:
      - '*.dll'
test_script:
  - copy .\LR4\str.txt C:\projects\kurs-ukpo\x64\Release\
  - vstest.console /logger:Appveyor x64\Release\UnitTest1.dll
  - vstest.console /logger:Appveyor x64\Release\UnitTest2.dll
